spring.application.name=muscleyn-backend

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/muscleyn
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

app.cors.allowed-origins=*

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


file.upload-dir=/opt/muscleyn/uploads/products

jwt.secret=muscleynSecretKeyMuscleynSecretKey123456
jwt.expiration=86400000

razorpay.key.id=YOUR_KEY_ID
razorpay.key.secret=YOUR_SECRET

# Contact enquiry email notifications
contact.email.notifications.enabled=false
contact.email.to=
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Multipart Upload File Size Limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB